Insert into Brand(name, logo) values ('Alfa Romeo', '../logos/3.png');
Insert into Brand(name, logo) values ('Alpina', '../logos/4.png');
Insert into Brand(name, logo) values ('Alpine', '../logos/13577.png');
Insert into Brand(name, logo) values ('Aston Martin', '../logos/707.png');
Insert into Brand(name, logo) values ('Audi', '../logos/5.png');
Insert into Brand(name, logo) values ('BMW', '../logos/7.png');
Insert into Brand(name, logo) values ('Buick', '../logos/12944.png');
Insert into Brand(name, logo) values ('Bugatti', '../logos/8.png');
Insert into Brand(name, logo) values ('Cadillac', '../logos/9.png');
Insert into Brand(name, logo) values ('Chevrolet', '../logos/10.png');
Insert into Brand(name, logo) values ('Chrysler', '../logos/11.png');
Insert into Brand(name, logo) values ('Citroën', '../logos/12.png');
Insert into Brand(name, logo) values ('Dacia', '../logos/13.png');
Insert into Brand(name, logo) values ('Daewoo', '../logos/14.png');
Insert into Brand(name, logo) values ('Dodge', '../logos/15.png');
Insert into Brand(name, logo) values ('DS', '../logos/10089.png');
Insert into Brand(name, logo) values ('Ferrari', '../logos/16.png');
Insert into Brand(name, logo) values ('Fiat', '../logos/17.png');
Insert into Brand(name, logo) values ('Ford', '../logos/18.png');
Insert into Brand(name, logo) values ('GWM', '../logos/8973.png');
Insert into Brand(name, logo) values ('Holden', '../logos/holden.png');
Insert into Brand(name, logo) values ('Honda', '../logos/19.png');
Insert into Brand(name, logo) values ('Hyundai', '../logos/20.png');
Insert into Brand(name, logo) values ('Infiniti', '../logos/21.png');
Insert into Brand(name, logo) values ('Isuzu', '../logos/1144.png');
Insert into Brand(name, logo) values ('Iveco', '../logos/1941.png');
Insert into Brand(name, logo) values ('Jaguar', '../logos/22.png');
Insert into Brand(name, logo) values ('Jeep', '../logos/23.png');
Insert into Brand(name, logo) values ('Kia', '../logos/24.png');
Insert into Brand(name, logo) values ('KTM', '../logos/25.png');
Insert into Brand(name, logo) values ('Lamborghini', '../logos/26.png');
Insert into Brand(name, logo) values ('Lancia', '../logos/27.png');
Insert into Brand(name, logo) values ('Landrover', '../logos/28.png');
Insert into Brand(name, logo) values ('Lexus', '../logos/9834.png');
Insert into Brand(name, logo) values ('Lotus', '../logos/29.png');
Insert into Brand(name, logo) values ('Mahindra', '../logos/10937.png');
Insert into Brand(name, logo) values ('MAN', '../logos/man.png');
Insert into Brand(name, logo) values ('Maserati', '../logos/30.png');
Insert into Brand(name, logo) values ('Mazda', '../logos/31.png');
Insert into Brand(name, logo) values ('McLaren', '../logos/1712.png');
Insert into Brand(name, logo) values ('Mercedes', '../logos/32.png');
Insert into Brand(name, logo) values ('Mini', '../logos/34.png');
Insert into Brand(name, logo) values ('Mitsubishi', '../logos/35.png');
Insert into Brand(name, logo) values ('Nissan', '../logos/36.png');
Insert into Brand(name, logo) values ('Opel', '../logos/37.png');
Insert into Brand(name, logo) values ('Pagani', '../logos/2852.png');
Insert into Brand(name, logo) values ('Peugeot', '../logos/38.png');
Insert into Brand(name, logo) values ('PGO', '../logos/6833.png');
Insert into Brand(name, logo) values ('Piaggio', '../logos/4967.png');
Insert into Brand(name, logo) values ('Porsche', '../logos/39.png');
Insert into Brand(name, logo) values ('Renault', '../logos/40.png');
Insert into Brand(name, logo) values ('Rolls Royce', '../logos/41.png');
Insert into Brand(name, logo) values ('Saab', '../logos/42.png');
Insert into Brand(name, logo) values ('Samsung', '../logos/samsung-renault.png');
Insert into Brand(name, logo) values ('Scion', '../logos/7456.png');
Insert into Brand(name, logo) values ('Seat', '../logos/43.png');
Insert into Brand(name, logo) values ('Skoda', '../logos/44.png');
Insert into Brand(name, logo) values ('Smart', '../logos/45.png');
Insert into Brand(name, logo) values ('SsangYong', '../logos/1034.png');
Insert into Brand(name, logo) values ('Subaru', '../logos/46.png');
Insert into Brand(name, logo) values ('Suzuki', '../logos/47.png');
Insert into Brand(name, logo) values ('Tata', '../logos/1035.png');
Insert into Brand(name, logo) values ('Toyota', '../logos/48.png');
Insert into Brand(name, logo) values ('Volkswagen', '../logos/50.png');
Insert into Brand(name, logo) values ('Volvo', '../logos/49.png');
Insert into Brand(name, logo) values ('Westfield', '../logos/5091.png');
Insert into Brand(name, logo) values ('Wiesmann', '../logos/51.png');
INSERT INTO Car (Brand,Model,BuildYear,MotorType,Fuel,OPower,OTorque,S1Power,S1Torque,S1DPower,S1DTorque,S1Price,S2Power,S2Torque,S2DPower,S2DTorque,S2Price,S3Power,S3Torque,S3DPower,S3DTorque,S3Price,S4Power,S4Torque,S4DPower,S4DTorque,S4Price,DOLControl,DORPMLimit,DOSTime,DS1LControl,DS1RPMLimit,DS1STime,DS1Price,DS2LControl,DS2RPMLimit,DS2STime,DS2Price,EEFReduction,EPrice) VALUES ('Alfa Romeo','147','2001 -> 2005','1.9Jtd','Diesel','115 Ps','275 Nm','145 Ps','330 Nm','+ 30 Ps','+ 55 Nm','410','','','','','','','','','','','','','','','','','','','','','','','','','','','+/- 10%','310');
INSERT INTO Car (Brand,Model,BuildYear,MotorType,Fuel,OPower,OTorque,S1Power,S1Torque,S1DPower,S1DTorque,S1Price,S2Power,S2Torque,S2DPower,S2DTorque,S2Price,S3Power,S3Torque,S3DPower,S3DTorque,S3Price,S4Power,S4Torque,S4DPower,S4DTorque,S4Price,DOLControl,DORPMLimit,DOSTime,DS1LControl,DS1RPMLimit,DS1STime,DS1Price,DS2LControl,DS2RPMLimit,DS2STime,DS2Price,EEFReduction,EPrice) VALUES ('Alfa Romeo','147','2001 -> 2005','1.9Jtd','Diesel','136 Ps','305 Nm','175 Ps','380 Nm','+ 39 Ps','+ 75 Nm','410','','','','','','','','','','','','','','','','','','','','','','','','','','','+/- 12%','310');
INSERT INTO Car (Brand,Model,BuildYear,MotorType,Fuel,OPower,OTorque,S1Power,S1Torque,S1DPower,S1DTorque,S1Price,S2Power,S2Torque,S2DPower,S2DTorque,S2Price,S3Power,S3Torque,S3DPower,S3DTorque,S3Price,S4Power,S4Torque,S4DPower,S4DTorque,S4Price,DOLControl,DORPMLimit,DOSTime,DS1LControl,DS1RPMLimit,DS1STime,DS1Price,DS2LControl,DS2RPMLimit,DS2STime,DS2Price,EEFReduction,EPrice) VALUES ('Alfa Romeo','147','2001 -> 2005','1.9Jtd','Diesel','140 Ps','305 Nm','175 Ps','380 Nm','+ 35 Ps','+ 75 Nm','410','','','','','','','','','','','','','','','','','','','','','','','','','','','+/- 12%','310');
INSERT INTO Car (Brand,Model,BuildYear,MotorType,Fuel,OPower,OTorque,S1Power,S1Torque,S1DPower,S1DTorque,S1Price,S2Power,S2Torque,S2DPower,S2DTorque,S2Price,S3Power,S3Torque,S3DPower,S3DTorque,S3Price,S4Power,S4Torque,S4DPower,S4DTorque,S4Price,DOLControl,DORPMLimit,DOSTime,DS1LControl,DS1RPMLimit,DS1STime,DS1Price,DS2LControl,DS2RPMLimit,DS2STime,DS2Price,EEFReduction,EPrice) VALUES ('Alfa Romeo','147','2005 -> ...','2.0 TS','Benzin','150 Ps','181 Nm','165 Ps','200 Nm','+ 15 Ps','+ 19 Nm','460','','','','','','','','','','','','','','','','','','','','','','','','','','','+/- 5%','360');
INSERT INTO Car (Brand,Model,BuildYear,MotorType,Fuel,OPower,OTorque,S1Power,S1Torque,S1DPower,S1DTorque,S1Price,S2Power,S2Torque,S2DPower,S2DTorque,S2Price,S3Power,S3Torque,S3DPower,S3DTorque,S3Price,S4Power,S4Torque,S4DPower,S4DTorque,S4Price,DOLControl,DORPMLimit,DOSTime,DS1LControl,DS1RPMLimit,DS1STime,DS1Price,DS2LControl,DS2RPMLimit,DS2STime,DS2Price,EEFReduction,EPrice) VALUES ('Alfa Romeo','147','2005 -> ...','3.2 V6 GTA','Benzin','250 Ps','300 Nm','275 Ps','325 Nm','+ 25 Ps','+ 25 Nm','630','','','','','','','','','','','','','','','','','','','','','','','','','','','+/- 4%','530');
INSERT INTO Car (Brand,Model,BuildYear,MotorType,Fuel,OPower,OTorque,S1Power,S1Torque,S1DPower,S1DTorque,S1Price,S2Power,S2Torque,S2DPower,S2DTorque,S2Price,S3Power,S3Torque,S3DPower,S3DTorque,S3Price,S4Power,S4Torque,S4DPower,S4DTorque,S4Price,DOLControl,DORPMLimit,DOSTime,DS1LControl,DS1RPMLimit,DS1STime,DS1Price,DS2LControl,DS2RPMLimit,DS2STime,DS2Price,EEFReduction,EPrice) VALUES ('Alfa Romeo','147','2005 -> ...','1.9Jtd','Diesel','100 Ps','200 Nm','135 Ps','265 Nm','+ 35 Ps','+ 65 Nm','410','','','','','','','','','','','','','','','','','','','','','','','','','','','+/- 16%','310');
INSERT INTO Car (Brand,Model,BuildYear,MotorType,Fuel,OPower,OTorque,S1Power,S1Torque,S1DPower,S1DTorque,S1Price,S2Power,S2Torque,S2DPower,S2DTorque,S2Price,S3Power,S3Torque,S3DPower,S3DTorque,S3Price,S4Power,S4Torque,S4DPower,S4DTorque,S4Price,DOLControl,DORPMLimit,DOSTime,DS1LControl,DS1RPMLimit,DS1STime,DS1Price,DS2LControl,DS2RPMLimit,DS2STime,DS2Price,EEFReduction,EPrice) VALUES ('Alfa Romeo','147','2005 -> ...','1.9Jtd','Diesel','115 Ps','275 Nm','150 Ps','350 Nm','+ 35 Ps','+ 75 Nm','460','','','','','','','','','','','','','','','','','','','','','','','','','','','+/- 14%','360');